name: Build and Test Shopping App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Show username
      run: echo daniel2212
    - name: Install Dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit

  run_ui_tests:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npm start
    - name: Run ui tests
      run: npm run test:ui
